
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Tue Jan 24 11:51:24 CET 2017
//----------------------------------------------------

package mini_c;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int CST = 3;
  public static final int IDENT = 2;
  public static final int LPAR = 5;
  public static final int EOF = 0;
  public static final int RB = 7;
  public static final int LB = 8;
  public static final int error = 1;
  public static final int SEMICOLON = 9;
  public static final int RPAR = 6;
  public static final int RETURN = 4;
}

