
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Tue Jan 31 15:59:49 CET 2017
//----------------------------------------------------

package mini_c;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int TIMES = 22;
  public static final int AND = 23;
  public static final int SIZEOF = 11;
  public static final int SEMICOLON = 16;
  public static final int ELSE = 6;
  public static final int IDENT = 2;
  public static final int NEG = 27;
  public static final int PLUS = 19;
  public static final int STRUCT = 10;
  public static final int OR = 24;
  public static final int INT = 8;
  public static final int EQUAL = 18;
  public static final int WHILE = 7;
  public static final int NOT = 25;
  public static final int RETURN = 9;
  public static final int IF = 5;
  public static final int LB = 15;
  public static final int RB = 14;
  public static final int COMMA = 17;
  public static final int CST = 3;
  public static final int EOF = 0;
  public static final int CMP = 4;
  public static final int DIV = 21;
  public static final int MINUS = 20;
  public static final int ARROW = 26;
  public static final int error = 1;
  public static final int RPAR = 13;
  public static final int LPAR = 12;
}

