
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Wed Jan 25 14:46:01 CET 2017
//----------------------------------------------------

package mini_c;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int TIMES = 16;
  public static final int AND = 17;
  public static final int SEMICOLON = 11;
  public static final int IDENT = 2;
  public static final int PLUS = 13;
  public static final int OR = 18;
  public static final int INT = 5;
  public static final int EQUAL = 12;
  public static final int NOT = 19;
  public static final int RETURN = 6;
  public static final int LB = 10;
  public static final int RB = 9;
  public static final int CST = 3;
  public static final int EOF = 0;
  public static final int CMP = 4;
  public static final int DIV = 15;
  public static final int MINUS = 14;
  public static final int error = 1;
  public static final int RPAR = 8;
  public static final int LPAR = 7;
}

